version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
 
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package

artifacts:
  files:
    - '**/*'
